### ISSUE TITLE
Some wrong !

### ISSUE THREAD

**Issue by emperinter** [mirucon/coldbox#110]
# I don't know how to say that,The theme not works on these days on my webiste,the search bar top bar not works on all device and menu bar not works on phone.At first, I thought I changed something for this,but when I get my backup.It still not work,when I git on Github,It works worse than I have.I can't understand why!Maybe I did some wrong!

[My website](https://www.emperinter.info/it)

**Comment by emperinter** [comment]
I thought something it works like CSS and another may need your service supported,your service is dead.It said something wrong like nginx when I preview  the theme

**Comment by mirucon** [comment]
I've fixed the issue with the search toggle button in the version 1.8.0. I don't know what is causing your problem when cloning the theme from GitHub unless you provide a detailed error log of Nginx. 
I'm closing this issue because this is not a problem of theme itself. You can post it to [WordPress.org forum](https://wordpress.org/support/forums/) if it persists so that you can get some help from volunteers.
